version: '3.8'

services:
  # 1. DATABASE (SQL Server)
  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FPT-Database
    restart: on-failure
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - sql_data:/var/opt/mssql
      - ./database/init.sql:/data/application/init.sql
      - ./database/init-db.sh:/data/application/init-db.sh
    networks:
      - FPT-Network

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FPT-Db-Init
    depends_on:
      - db-server
    volumes:
      - ./database/init.sql:/data/application/init.sql
      - ./database/init-db.sh:/data/application/init-db.sh
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: /bin/bash /data/application/init-db.sh
    networks:
      - FPT-Network

  # 2. BACKEND
  backend:
    image: phongnguyen04/fpteventmanagement-backend
    container_name: FPT-BackEnd
    restart: always
    environment:
      - CATALINA_OPTS=--add-opens java.base/java.time=ALL-UNNAMED
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - FPT-Network

  # 3. FRONTEND
  frontend:
    image: phongnguyen04/fpteventmanagement-frontend
    container_name: FPT-FrontEnd
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - FPT-Network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /app/node_modules

networks:
  FPT-Network:
    driver: bridge

volumes:
  sql_data: