version: '3.8'

services:
  #=== Backend ===
  backend:
    env_file:
      - ./docker-compose-env/backend.app.env
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: FPT-Event-Management-Backend
    environment:
      - CATALINA_OPTS=--add-opens java.base/java.time=ALL-UNNAMED
    ports:
      - "8080:8080"
    networks:
      - FPT-Network
    restart: on-failure
  
  #=== Frontend ===
  frontend:
    stdin_open: true
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: FPT-Event-Management-Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - FPT-Network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /app/node_modules
      - ./FrontEnd:/app
    restart: on-failure

networks:
  FPT-Network:
    driver: bridge