version: '3.8'

services:
  #=== Database ===
  db-server:
    env_file: ./docker-compose-env/database.env
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FPT-Database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - sql_data:/var/opt/mssql
      - ./database/init.sql:/data/application/init.sql
      - ./database/init-db.sh:/data/application/init-db.sh
   # command: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Admin12345! -Q "CREATE LOGIN [admin] WITH PASSWORD = 'Admin12345!', DEFAULT_DATABASE = [FPTEventManagement]; USE [FPTEventManagement]; CREATE USER [admin] FOR LOGIN [admin]; ALTER ROLE [db_owner] ADD MEMBER [admin];"
    networks:
      - FPT-Network
    restart: on-failure
  
  db-init:
    env_file:
      - ./docker-compose-env/database.env
      - ./docker-compose-env/backend.env
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FPT-DB-Init
    depends_on: 
      - db-server
    volumes:
      - ./database/init.sql:/data/application/init.sql
      - ./database/init-db.sh:/data/application/init-db.sh
    entrypoint: /bin/bash /data/application/init-db.sh
    networks:
      - FPT-Network

  #=== Backend ===
  backend:
    env_file:
      - ./docker-compose-env/backend.env
      - ./docker-compose-env/database.env
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: phongnguyen04/fpteventmanagement-backend
    container_name: FPT-Event-Management-Backend
    environment:
      - CATALINA_OPTS=--add-opens java.base/java.time=ALL-UNNAMED
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - FPT-Network
    restart: on-failure
  
  #=== Frontend ===
  frontend:
    stdin_open: true
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    image: phongnguyen04/fpteventmanagement-frontend
    container_name: FPT-Event-Management-Frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - FPT-Network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /app/node_modules
      - ./FrontEnd:/app
    restart: on-failure

networks:
  FPT-Network:
    driver: bridge

volumes:
  sql_data: